package com.qaprosoft.carina.work.mobile.gui.pages.constants;

public interface IConstants {
    public static final int ONE_SECOND = 1;
    public static final int THREE_SECONDS = 3;
    public static final int FIVE_SECONDS = 5;
    public static final int TEN_SECONDS = 10;
    public static final int THREE_TIMEOUT = 3;
    public static final int TEN_TIMEOUT = 10;
    public static final int TWENTY_TIMEOUT = 10;
    public static final boolean TRUE = true;
    public static final boolean FALSE = false;
    public static final int FIRST = 0;
    public static final String MALE = "Male";
    public static final String FEMALE = "Female";
    public static final int TWENTY_YEARS_OLD = 20;
    public static final int FAST_SWIPES = 300;
    public static final int NORMAL_SWIPES = 600;
    public static final int SLOW_SWIPES = 1200;
    public static final int TEN_SWIPES = 10;
    public static final int FIVE_SWIPES = 5;
    public static final int ZIP_CODE = 98165;
    public static final int SIX_FEET = 6;
    public static final int TWO_INCHES = 2;
    public static final int CENTIMETERS_177 = 177;
    public static final int KILOGRAMS_75 = 75;
    public static final int KILOGRAMS_70 = 70;
    public static final int POUNDS_155 = 155;
    public static final int POUNDS_145 = 145;
    public static final int STONE_12 = 12;
    public static final int STONE_11 = 11;
    public static final int POUNDS_8 = 8;
    public static final int POUNDS_12 = 12;
    public static final String JUST_NUMBERS = "0123456789";
    public static final String JUST_LOWER_CASE_LETTERS = "itriedsohard";
    public static final String JUST_UPPER_CASE_LETTERS = "ANDGOTSOFAR";
    public static final String JUST_SPECIAL_SYMBOLS = "!@#$%^&*()_+=";
    public static final String MIXED_PASSWORD = "Cs50!hU&Y2)";
    public static final String SHORT_PASSWORD = "short";
    public static final String CORRECT_EMAIL = "such@email.com";
    public static final String INCORRECT_EMAIL = "wrong.email.gmail.com";
}
